#include <HUSIS.h>

void Teclado_EnUsIntl()
{
    Teclado_Registra     (0x2a,  0 , TECLA_ESPECIAL_SHIFT | TECLA_ESPECIAL_ESQUERDA);
    Teclado_Registra     (0x36,  0 , TECLA_ESPECIAL_SHIFT | TECLA_ESPECIAL_DIREITA);
    Teclado_Registra     (0xe0,  0 , TECLA_EXTENDIDO);
    Teclado_Registra     (0x1d,  0 , TECLA_ESPECIAL_CTRL);
    Teclado_Registra     (0x38,  0 , TECLA_ESPECIAL_ALT | TECLA_ESPECIAL_ESQUERDA);
    Teclado_RegistraExt  (0x38,  0 , TECLA_ESPECIAL_ALT | TECLA_ESPECIAL_DIREITA);
    Teclado_Registra     (0x3a,  0 , TECLA_ESPECIAL_CAPS);


    Teclado_Registra     (0x01,  0 , TECLA_ESC);
    Teclado_Registra     (0x39, ' ', TECLA_ESPACO);
    Teclado_Registra     (0x29, '`', TECLA_APOSTROFO);
    Teclado_RegistraShift(0x29, '~', TECLA_TIL);
    Teclado_Registra     (0x02, '1', TECLA_1);
    Teclado_RegistraShift(0x02, '!', TECLA_EXCLAMACAO);
    Teclado_Registra     (0x03, '2', TECLA_2);
    Teclado_RegistraShift(0x03, '@', TECLA_ARROBA);
    Teclado_Registra     (0x04, '3', TECLA_3);
    Teclado_RegistraShift(0x04, '#', TECLA_CERQUILHA);
    Teclado_Registra     (0x05, '4', TECLA_4);
    Teclado_RegistraShift(0x05, '$', TECLA_CIFRAO);
    Teclado_Registra     (0x06, '5', TECLA_5);
    Teclado_RegistraShift(0x06, '%', TECLA_PORCENTAGEM);
    Teclado_Registra     (0x07, '6', TECLA_6);
    Teclado_RegistraShift(0x07, '^', TECLA_CIRCUNFLEXO);
    Teclado_Registra     (0x08, '7', TECLA_7);
    Teclado_RegistraShift(0x08, '&', TECLA_E_COMERCIAL);
    Teclado_Registra     (0x09, '8', TECLA_8);
    Teclado_RegistraShift(0x09, '*', TECLA_ASTERISCO);
    Teclado_Registra     (0x0a, '9', TECLA_9);
    Teclado_RegistraShift(0x0a, '(', TECLA_PARENTESES_ABRE);
    Teclado_Registra     (0x0b, '0', TECLA_0);
    Teclado_RegistraShift(0x0b, ')', TECLA_PARENTESES_FECHA);
    Teclado_Registra     (0x0c, '-', TECLA_MENOS);
    Teclado_RegistraShift(0x0c, '_', TECLA_SUBSCRITO);
    Teclado_Registra     (0x0d, '=', TECLA_IGUAL);
    Teclado_RegistraShift(0x0d, '+', TECLA_MAIS);
    Teclado_Registra     (0x0e,  8 , TECLA_BACKSPACE);
    Teclado_RegistraShift(0x0e,  0 , TECLA_DELETE);
    Teclado_RegistraExt  (0x53,  0 , TECLA_DELETE);
    Teclado_Registra     (0x0f,  9 , TECLA_TAB);
    Teclado_Registra     (0x10, 'q', TECLA_Q);
    Teclado_RegistraShift(0x10, 'Q', TECLA_Q);
    Teclado_Registra     (0x11, 'w', TECLA_W);
    Teclado_RegistraShift(0x11, 'W', TECLA_W);
    Teclado_Registra     (0x12, 'e', TECLA_E);
    Teclado_RegistraShift(0x12, 'E', TECLA_E);
    Teclado_Registra     (0x13, 'r', TECLA_R);
    Teclado_RegistraShift(0x13, 'R', TECLA_R);
    Teclado_Registra     (0x14, 't', TECLA_T);
    Teclado_RegistraShift(0x14, 'T', TECLA_T);
    Teclado_Registra     (0x15, 'y', TECLA_Y);
    Teclado_RegistraShift(0x15, 'Y', TECLA_Y);
    Teclado_Registra     (0x16, 'u', TECLA_U);
    Teclado_RegistraShift(0x16, 'U', TECLA_U);
    Teclado_Registra     (0x17, 'i', TECLA_I);
    Teclado_RegistraShift(0x17, 'I', TECLA_I);
    Teclado_Registra     (0x18, 'o', TECLA_O);
    Teclado_RegistraShift(0x18, 'O', TECLA_O);
    Teclado_Registra     (0x19, 'p', TECLA_P);
    Teclado_RegistraShift(0x19, 'P', TECLA_P);
    Teclado_Registra     (0x1a, '[', TECLA_COLCHETES_ABRE);
    Teclado_RegistraShift(0x1a, '{', TECLA_CHAVES_ABRE);
    Teclado_Registra     (0x1b, ']', TECLA_COLCHETES_FECHA);
    Teclado_RegistraShift(0x1b, '}', TECLA_CHAVES_FECHA);
    Teclado_Registra     (0x2b, '\\', TECLA_BARRA_INVERTIDA);
    Teclado_RegistraShift(0x2b, '|', TECLA_BARRA_VERTICAL);
    Teclado_Registra     (0x1e, 'a', TECLA_A);
    Teclado_RegistraShift(0x1e, 'A', TECLA_A);
    Teclado_Registra     (0x1f, 's', TECLA_S);
    Teclado_RegistraShift(0x1f, 'S', TECLA_S);
    Teclado_Registra     (0x20, 'd', TECLA_D);
    Teclado_RegistraShift(0x20, 'D', TECLA_D);
    Teclado_Registra     (0x21, 'f', TECLA_F);
    Teclado_RegistraShift(0x21, 'F', TECLA_F);
    Teclado_Registra     (0x22, 'g', TECLA_G);
    Teclado_RegistraShift(0x22, 'G', TECLA_G);
    Teclado_Registra     (0x23, 'h', TECLA_H);
    Teclado_RegistraShift(0x23, 'H', TECLA_H);
    Teclado_Registra     (0x24, 'j', TECLA_J);
    Teclado_RegistraShift(0x24, 'J', TECLA_J);
    Teclado_Registra     (0x25, 'k', TECLA_K);
    Teclado_RegistraShift(0x25, 'K', TECLA_K);
    Teclado_Registra     (0x26, 'l', TECLA_L);
    Teclado_RegistraShift(0x26, 'L', TECLA_L);
    Teclado_Registra     (0x27, ';', TECLA_PONTO_E_VIRGULA);
    Teclado_RegistraShift(0x27, ':', TECLA_DOIS_PONTOS);
    Teclado_Registra     (0x28, '\'', TECLA_ASPAS_SIMPLES);
    Teclado_RegistraShift(0x28, '\"', TECLA_ASPAS_DUPLAS);
    Teclado_Registra     (0x1c, 10, TECLA_ENTER);
    Teclado_RegistraShift(0x1c, 13, TECLA_ENTER);
    Teclado_Registra     (0x2c, 'z', TECLA_Z);
    Teclado_RegistraShift(0x2c, 'Z', TECLA_Z);
    Teclado_Registra     (0x2d, 'x', TECLA_X);
    Teclado_RegistraShift(0x2d, 'X', TECLA_X);
    Teclado_Registra     (0x2e, 'c', TECLA_C);
    Teclado_RegistraShift(0x2e, 'C', TECLA_C);
    Teclado_Registra     (0x2f, 'v', TECLA_V);
    Teclado_RegistraShift(0x2f, 'V', TECLA_V);
    Teclado_Registra     (0x30, 'b', TECLA_B);
    Teclado_RegistraShift(0x30, 'B', TECLA_B);
    Teclado_Registra     (0x31, 'n', TECLA_N);
    Teclado_RegistraShift(0x31, 'N', TECLA_N);
    Teclado_Registra     (0x32, 'm', TECLA_M);
    Teclado_RegistraShift(0x32, 'M', TECLA_M);
    Teclado_Registra     (0x33, ',', TECLA_VIRGULA);
    Teclado_RegistraShift(0x33, '<', TECLA_MENOR_QUE);
    Teclado_Registra     (0x34, '.', TECLA_PONTO);
    Teclado_RegistraShift(0x34, '>', TECLA_MAIOR_QUE);
    Teclado_Registra     (0x35, '/', TECLA_BARRA);
    Teclado_RegistraShift(0x35, '?', TECLA_INTERROGACAO);
    Teclado_Registra     (0x48,  0 , TECLA_SETA_ACIMA);
    Teclado_RegistraShift(0x48,  0 , TECLA_SETA_ACIMA);
    Teclado_Registra     (0x50,  0 , TECLA_SETA_ABAIXO);
    Teclado_RegistraShift(0x50,  0 , TECLA_SETA_ABAIXO);
    Teclado_Registra     (0x4b,  0 , TECLA_SETA_ESQUERDA);
    Teclado_RegistraShift(0x4b,  0 , TECLA_SETA_ESQUERDA);
    Teclado_Registra     (0x4d,  0 , TECLA_SETA_DIREITA);
    Teclado_RegistraShift(0x4d,  0 , TECLA_SETA_DIREITA);
}